
INSERT OVERWRITE TABLE s_crm_mb_member_points_coupon_deal PARTITION(ds='${bdp.system.bizdae}')
SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
coupon_name,
cost_points,
cost_time,
member_id,
contact_id,
coupon_info_id,
tq_command,
channel,
tq_coupon_name,
coupon_config_id,
person_id,
brand_contact_id
FROM    (
            SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
coupon_name,
cost_points,
cost_time,
member_id,
contact_id,
coupon_info_id,
tq_command,
channel,
tq_coupon_name,
coupon_config_id,
person_id,
brand_contact_id
                    ,ROW_NUMBER() OVER(PARTITION BY a.id ORDER BY a.update_time DESC ) AS num
            FROM    (
                        SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
coupon_name,
cost_points,
cost_time,
member_id,
contact_id,
coupon_info_id,
tq_command,
channel,
tq_coupon_name,
coupon_config_id,
person_id,
brand_contact_id
                        FROM    s_crm_mb_member_points_coupon_deal
                        WHERE   ds = '${befor_yesteday}'
                        UNION ALL
                        SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
coupon_name,
cost_points,
cost_time,
member_id,
contact_id,
coupon_info_id,
tq_command,
channel,
tq_coupon_name,
coupon_config_id,
person_id,
brand_contact_id
                        FROM    s_crm_mb_member_points_coupon_deal_delta
                        WHERE   ds = '${bdp.system.bizdae}'
                    ) a
        ) b
WHERE   num = 1
;

INSERT OVERWRITE TABLE s_crm_mb_member_points_log PARTITION(ds='${bdp.system.bizdae}')
SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
member_id,
person_id,
brand_id,
exchange_points,
exchange_time,
operator,
reason,
detail_reason,
order_num,
note,
total_points,
points_log_left,
use_all,
crm_store_id,
operator_name,
store_id,
store_name,
travel_city_id,
travel_city_name,
area_id,
area_name,
business_format_name,
business_format_id,
system_id,
crm_order_num,
order_screen_shot_address,
outer_guide_id
FROM    (
            SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
member_id,
person_id,
brand_id,
exchange_points,
exchange_time,
operator,
reason,
detail_reason,
order_num,
note,
total_points,
points_log_left,
use_all,
crm_store_id,
operator_name,
store_id,
store_name,
travel_city_id,
travel_city_name,
area_id,
area_name,
business_format_name,
business_format_id,
system_id,
crm_order_num,
order_screen_shot_address,
outer_guide_id
                    ,ROW_NUMBER() OVER(PARTITION BY a.id ORDER BY a.update_time DESC ) AS num
            FROM    (
                        SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
member_id,
person_id,
brand_id,
exchange_points,
exchange_time,
operator,
reason,
detail_reason,
order_num,
note,
total_points,
points_log_left,
use_all,
crm_store_id,
operator_name,
store_id,
store_name,
travel_city_id,
travel_city_name,
area_id,
area_name,
business_format_name,
business_format_id,
system_id,
crm_order_num,
order_screen_shot_address,
outer_guide_id
                        FROM    s_crm_mb_member_points_log
                        WHERE   ds = '${befor_yesteday}'
                        UNION ALL
                        SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
member_id,
person_id,
brand_id,
exchange_points,
exchange_time,
operator,
reason,
detail_reason,
order_num,
note,
total_points,
points_log_left,
use_all,
crm_store_id,
operator_name,
store_id,
store_name,
travel_city_id,
travel_city_name,
area_id,
area_name,
business_format_name,
business_format_id,
system_id,
crm_order_num,
order_screen_shot_address,
outer_guide_id
                        FROM    s_crm_mb_member_points_log_delta
                        WHERE   ds = '${bdp.system.bizdae}'
                    ) a
        ) b
WHERE   num = 1
;

INSERT OVERWRITE TABLE s_crm_sfso_t_order PARTITION(ds='${bdp.system.bizdae}')
SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
system_id,
member_no,
mobile,
out_order_no,
trade_id,
amount,
discount_amount,
pay_amount,
user_card_code,
travel_city_id,
business_format_id,
area_id,
store_id,
terminal_id,
ticket_shop_id,
seller,
product_id,
product_name,
product_quantity,
product_price,
valid_begin_time,
valid_end_time,
valid_day,
product_code,
order_time,
del_flag,
order_type,
person_id,
brand_id,
extend_info,
product_category,
night_audit_amount,
crs_order_no
FROM    (
            SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
system_id,
member_no,
mobile,
out_order_no,
trade_id,
amount,
discount_amount,
pay_amount,
user_card_code,
travel_city_id,
business_format_id,
area_id,
store_id,
terminal_id,
ticket_shop_id,
seller,
product_id,
product_name,
product_quantity,
product_price,
valid_begin_time,
valid_end_time,
valid_day,
product_code,
order_time,
del_flag,
order_type,
person_id,
brand_id,
extend_info,
product_category,
night_audit_amount,
crs_order_no
                    ,ROW_NUMBER() OVER(PARTITION BY a.id ORDER BY a.update_time DESC ) AS num
            FROM    (
                        SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
system_id,
member_no,
mobile,
out_order_no,
trade_id,
amount,
discount_amount,
pay_amount,
user_card_code,
travel_city_id,
business_format_id,
area_id,
store_id,
terminal_id,
ticket_shop_id,
seller,
product_id,
product_name,
product_quantity,
product_price,
valid_begin_time,
valid_end_time,
valid_day,
product_code,
order_time,
del_flag,
order_type,
person_id,
brand_id,
extend_info,
product_category,
night_audit_amount,
crs_order_no
                        FROM    s_crm_sfso_t_order
                        WHERE   ds = '${befor_yesteday}'
                        UNION ALL
                        SELECT  id,
tenant_id,
organization,
owner,
creator,
updater,
position,
create_time,
update_time,
startTime,
finishTime,
system_id,
member_no,
mobile,
out_order_no,
trade_id,
amount,
discount_amount,
pay_amount,
user_card_code,
travel_city_id,
business_format_id,
area_id,
store_id,
terminal_id,
ticket_shop_id,
seller,
product_id,
product_name,
product_quantity,
product_price,
valid_begin_time,
valid_end_time,
valid_day,
product_code,
order_time,
del_flag,
order_type,
person_id,
brand_id,
extend_info,
product_category,
night_audit_amount,
crs_order_no
                        FROM    s_crm_sfso_t_order_delta
                        WHERE   ds = '${bdp.system.bizdae}'
                    ) a
        ) b
WHERE   num = 1
;

INSERT OVERWRITE TABLE s_crm_tt_tenant_wechat_3rd_info PARTITION(ds='${bdp.system.bizdae}')
SELECT  id,
tenant_id,
authorizer_appid,
is_authorization_canceled,
is_fans_sync_opened,
fans_sync_period,
authorizer_refresh_token,
nick_name,
head_img,
service_type_info,
verify_type_info,
original_user_name,
principal_name,
alias,
is_open_store,
is_open_scan,
is_open_pay,
is_open_card,
is_open_shake,
qrcode_url,
funcscope_category,
create_time,
update_time,
last_sync_time,
union_type,
is_default,
mch_id,
api_key,
brand_id,
cert_path
FROM    (
            SELECT  id,
tenant_id,
authorizer_appid,
is_authorization_canceled,
is_fans_sync_opened,
fans_sync_period,
authorizer_refresh_token,
nick_name,
head_img,
service_type_info,
verify_type_info,
original_user_name,
principal_name,
alias,
is_open_store,
is_open_scan,
is_open_pay,
is_open_card,
is_open_shake,
qrcode_url,
funcscope_category,
create_time,
update_time,
last_sync_time,
union_type,
is_default,
mch_id,
api_key,
brand_id,
cert_path
                    ,ROW_NUMBER() OVER(PARTITION BY a.id ORDER BY a.update_time DESC ) AS num
            FROM    (
                        SELECT  id,
tenant_id,
authorizer_appid,
is_authorization_canceled,
is_fans_sync_opened,
fans_sync_period,
authorizer_refresh_token,
nick_name,
head_img,
service_type_info,
verify_type_info,
original_user_name,
principal_name,
alias,
is_open_store,
is_open_scan,
is_open_pay,
is_open_card,
is_open_shake,
qrcode_url,
funcscope_category,
create_time,
update_time,
last_sync_time,
union_type,
is_default,
mch_id,
api_key,
brand_id,
cert_path
                        FROM    s_crm_tt_tenant_wechat_3rd_info
                        WHERE   ds = '${befor_yesteday}'
                        UNION ALL
                        SELECT  id,
tenant_id,
authorizer_appid,
is_authorization_canceled,
is_fans_sync_opened,
fans_sync_period,
authorizer_refresh_token,
nick_name,
head_img,
service_type_info,
verify_type_info,
original_user_name,
principal_name,
alias,
is_open_store,
is_open_scan,
is_open_pay,
is_open_card,
is_open_shake,
qrcode_url,
funcscope_category,
create_time,
update_time,
last_sync_time,
union_type,
is_default,
mch_id,
api_key,
brand_id,
cert_path
                        FROM    s_crm_tt_tenant_wechat_3rd_info_delta
                        WHERE   ds = '${bdp.system.bizdae}'
                    ) a
        ) b
WHERE   num = 1
;
